language: ruby
cache: bundler
sudo: required
dist: trusty
os:
  - linux

branches:
  only:
    - develop
    - master
    - /^release.*$/

addons:
  apt:
    packages:
      - git
  ssh_known_hosts: staging.paddlepaddle.org

install:
  - bundle install

script:
  - |
    export DEPLOY_DOCS_SH=https://raw.githubusercontent.com/PaddlePaddle/PaddlePaddle.org/deploy_blog/scripts/deploy/deploy_docs.sh  # change branch
    export BLOG_DIR=`pwd`
    echo "blog dir = $BLOG_DIR"
    cd ..
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "add_travis_ci_for_blog"  ||  "$TRAVIS_BRANCH" =~ ^v[[:digit:]]+\.[[:digit:]]+(\.[[:digit:]]+)?(-\S*)?$ ]]; then echo "YES!!!"; else echo "not develop branch, no deploy"; fi;

notifications:
  email:
    on_success: change
    on_failure: always