language: ruby
cache: ccache
sudo: required
dist: trusty
os:
  - linux

rvm:
  - 2.4.1

addons:
  ssh_known_hosts: 13.229.163.131

install:
  - rvm install 2.4.1
  - rvm use 2.4.1
  - gem install bundler
  - bundle check || bundle install

script:
  - |
    export DEPLOY_DOCS_SH=https://raw.githubusercontent.com/PaddlePaddle/PaddlePaddle.org/master/scripts/deploy/deploy_docs.sh
    export BLOG_DIR=`pwd`
    cd ..
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]] || [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "not master branch, no deploy"; exit 0; fi;
    curl $DEPLOY_DOCS_SH | bash -s $CONTENT_DEC_PASSWD $TRAVIS_BRANCH $BLOG_DIR

notifications:
  email:
    on_success: change
    on_failure: always
